/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'status' : string,
  'balance' : bigint,
  'accountId' : string,
  'createdAt' : bigint,
  'accountType' : { 'creditCard' : null } |
    { 'homeLoan' : null } |
    { 'investment' : null } |
    { 'insurance' : null } |
    { 'savings' : null } |
    { 'current' : null },
  'accountNumber' : string,
}
export interface DashboardSummary {
  'recentTransactions' : Array<Transaction>,
  'unreadMessageCount' : bigint,
  'totalBalance' : bigint,
  'accountCount' : bigint,
}
export interface FundTransferInput {
  'description' : string,
  'toAccountId' : string,
  'fromAccountId' : string,
  'amount' : bigint,
}
export interface Message {
  'messageId' : string,
  'subject' : string,
  'createdAt' : bigint,
  'messageStatus' : { 'read' : null } |
    { 'unread' : null },
  'messageText' : string,
}
export interface Payee {
  'ifsc' : string,
  'payeeName' : string,
  'bankName' : string,
  'accountNumber' : string,
  'branchName' : string,
  'payeeId' : string,
}
export interface PaymentInput {
  'description' : string,
  'targetAccountId' : string,
  'amount' : bigint,
  'sourceAccountId' : string,
}
export interface Transaction {
  'status' : { 'disputed' : null } |
    { 'pending' : null } |
    { 'completed' : null },
  'transactionType' : { 'transfer' : null } |
    { 'payment' : null },
  'date' : bigint,
  'description' : string,
  'toAccountId' : string,
  'fromAccountId' : string,
  'amount' : bigint,
  'transactionId' : string,
}
export interface TransactionsFilter {
  'status' : [] | [
    { 'disputed' : null } |
      { 'pending' : null } |
      { 'completed' : null }
  ],
  'fromAmount' : [] | [bigint],
  'toDate' : [] | [bigint],
  'toAccountId' : [] | [string],
  'fromAccountId' : [] | [string],
  'fromDate' : [] | [bigint],
  'toAmount' : [] | [bigint],
}
export interface UserProfile {
  'dateOfBirth' : string,
  'name' : string,
  'email' : string,
  'preferences' : string,
  'kycStatus' : boolean,
  'address' : string,
  'phoneNumber' : string,
  'idProofBlobId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccount' : ActorMethod<[Account], undefined>,
  'addPayee' : ActorMethod<[Payee], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMessage' : ActorMethod<[Message], undefined>,
  'deleteAccount' : ActorMethod<[string], undefined>,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'deletePayee' : ActorMethod<[string], undefined>,
  'disputeTransaction' : ActorMethod<[string], undefined>,
  'filterTransactions' : ActorMethod<
    [TransactionsFilter, bigint],
    Array<Transaction>
  >,
  'fundTransfer' : ActorMethod<[FundTransferInput], undefined>,
  'getAccount' : ActorMethod<[string], Account>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getMessage' : ActorMethod<[string], Message>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAccounts' : ActorMethod<[], Array<Account>>,
  'listMessages' : ActorMethod<[], Array<Message>>,
  'listPayees' : ActorMethod<[], Array<Payee>>,
  'listTransactions' : ActorMethod<[], Array<Transaction>>,
  'markRead' : ActorMethod<[string], undefined>,
  'markUnread' : ActorMethod<[string], undefined>,
  'processPayment' : ActorMethod<[PaymentInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setKycStatus' : ActorMethod<[boolean], undefined>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];