/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Account = IDL.Record({
  'status' : IDL.Text,
  'balance' : IDL.Int,
  'accountId' : IDL.Text,
  'createdAt' : IDL.Int,
  'accountType' : IDL.Variant({
    'creditCard' : IDL.Null,
    'homeLoan' : IDL.Null,
    'investment' : IDL.Null,
    'insurance' : IDL.Null,
    'savings' : IDL.Null,
    'current' : IDL.Null,
  }),
  'accountNumber' : IDL.Text,
});
export const Payee = IDL.Record({
  'ifsc' : IDL.Text,
  'payeeName' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'branchName' : IDL.Text,
  'payeeId' : IDL.Text,
});
export const Transaction = IDL.Record({
  'status' : IDL.Variant({
    'disputed' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'transactionType' : IDL.Variant({
    'transfer' : IDL.Null,
    'payment' : IDL.Null,
  }),
  'date' : IDL.Int,
  'description' : IDL.Text,
  'toAccountId' : IDL.Text,
  'fromAccountId' : IDL.Text,
  'amount' : IDL.Int,
  'transactionId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Message = IDL.Record({
  'messageId' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'messageStatus' : IDL.Variant({ 'read' : IDL.Null, 'unread' : IDL.Null }),
  'messageText' : IDL.Text,
});
export const TransactionsFilter = IDL.Record({
  'status' : IDL.Opt(
    IDL.Variant({
      'disputed' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
    })
  ),
  'fromAmount' : IDL.Opt(IDL.Int),
  'toDate' : IDL.Opt(IDL.Int),
  'toAccountId' : IDL.Opt(IDL.Text),
  'fromAccountId' : IDL.Opt(IDL.Text),
  'fromDate' : IDL.Opt(IDL.Int),
  'toAmount' : IDL.Opt(IDL.Int),
});
export const FundTransferInput = IDL.Record({
  'description' : IDL.Text,
  'toAccountId' : IDL.Text,
  'fromAccountId' : IDL.Text,
  'amount' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferences' : IDL.Text,
  'kycStatus' : IDL.Bool,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'idProofBlobId' : IDL.Opt(IDL.Text),
});
export const DashboardSummary = IDL.Record({
  'recentTransactions' : IDL.Vec(Transaction),
  'unreadMessageCount' : IDL.Nat,
  'totalBalance' : IDL.Int,
  'accountCount' : IDL.Nat,
});
export const PaymentInput = IDL.Record({
  'description' : IDL.Text,
  'targetAccountId' : IDL.Text,
  'amount' : IDL.Int,
  'sourceAccountId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccount' : IDL.Func([Account], [], []),
  'addPayee' : IDL.Func([Payee], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMessage' : IDL.Func([Message], [], []),
  'deleteAccount' : IDL.Func([IDL.Text], [], []),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'deletePayee' : IDL.Func([IDL.Text], [], []),
  'disputeTransaction' : IDL.Func([IDL.Text], [], []),
  'filterTransactions' : IDL.Func(
      [TransactionsFilter, IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'fundTransfer' : IDL.Func([FundTransferInput], [], []),
  'getAccount' : IDL.Func([IDL.Text], [Account], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getMessage' : IDL.Func([IDL.Text], [Message], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'listMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'listPayees' : IDL.Func([], [IDL.Vec(Payee)], ['query']),
  'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'markRead' : IDL.Func([IDL.Text], [], []),
  'markUnread' : IDL.Func([IDL.Text], [], []),
  'processPayment' : IDL.Func([PaymentInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setKycStatus' : IDL.Func([IDL.Bool], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Account = IDL.Record({
    'status' : IDL.Text,
    'balance' : IDL.Int,
    'accountId' : IDL.Text,
    'createdAt' : IDL.Int,
    'accountType' : IDL.Variant({
      'creditCard' : IDL.Null,
      'homeLoan' : IDL.Null,
      'investment' : IDL.Null,
      'insurance' : IDL.Null,
      'savings' : IDL.Null,
      'current' : IDL.Null,
    }),
    'accountNumber' : IDL.Text,
  });
  const Payee = IDL.Record({
    'ifsc' : IDL.Text,
    'payeeName' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'branchName' : IDL.Text,
    'payeeId' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'status' : IDL.Variant({
      'disputed' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'transactionType' : IDL.Variant({
      'transfer' : IDL.Null,
      'payment' : IDL.Null,
    }),
    'date' : IDL.Int,
    'description' : IDL.Text,
    'toAccountId' : IDL.Text,
    'fromAccountId' : IDL.Text,
    'amount' : IDL.Int,
    'transactionId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Message = IDL.Record({
    'messageId' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'messageStatus' : IDL.Variant({ 'read' : IDL.Null, 'unread' : IDL.Null }),
    'messageText' : IDL.Text,
  });
  const TransactionsFilter = IDL.Record({
    'status' : IDL.Opt(
      IDL.Variant({
        'disputed' : IDL.Null,
        'pending' : IDL.Null,
        'completed' : IDL.Null,
      })
    ),
    'fromAmount' : IDL.Opt(IDL.Int),
    'toDate' : IDL.Opt(IDL.Int),
    'toAccountId' : IDL.Opt(IDL.Text),
    'fromAccountId' : IDL.Opt(IDL.Text),
    'fromDate' : IDL.Opt(IDL.Int),
    'toAmount' : IDL.Opt(IDL.Int),
  });
  const FundTransferInput = IDL.Record({
    'description' : IDL.Text,
    'toAccountId' : IDL.Text,
    'fromAccountId' : IDL.Text,
    'amount' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferences' : IDL.Text,
    'kycStatus' : IDL.Bool,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'idProofBlobId' : IDL.Opt(IDL.Text),
  });
  const DashboardSummary = IDL.Record({
    'recentTransactions' : IDL.Vec(Transaction),
    'unreadMessageCount' : IDL.Nat,
    'totalBalance' : IDL.Int,
    'accountCount' : IDL.Nat,
  });
  const PaymentInput = IDL.Record({
    'description' : IDL.Text,
    'targetAccountId' : IDL.Text,
    'amount' : IDL.Int,
    'sourceAccountId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccount' : IDL.Func([Account], [], []),
    'addPayee' : IDL.Func([Payee], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMessage' : IDL.Func([Message], [], []),
    'deleteAccount' : IDL.Func([IDL.Text], [], []),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'deletePayee' : IDL.Func([IDL.Text], [], []),
    'disputeTransaction' : IDL.Func([IDL.Text], [], []),
    'filterTransactions' : IDL.Func(
        [TransactionsFilter, IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'fundTransfer' : IDL.Func([FundTransferInput], [], []),
    'getAccount' : IDL.Func([IDL.Text], [Account], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getMessage' : IDL.Func([IDL.Text], [Message], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'listMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'listPayees' : IDL.Func([], [IDL.Vec(Payee)], ['query']),
    'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'markRead' : IDL.Func([IDL.Text], [], []),
    'markUnread' : IDL.Func([IDL.Text], [], []),
    'processPayment' : IDL.Func([PaymentInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setKycStatus' : IDL.Func([IDL.Bool], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };