/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Payee {
    ifsc: string;
    payeeName: string;
    bankName: string;
    accountNumber: string;
    branchName: string;
    payeeId: string;
}
export interface Account {
    status: string;
    balance: bigint;
    accountId: string;
    createdAt: bigint;
    accountType: Variant_creditCard_homeLoan_investment_insurance_savings_current;
    accountNumber: string;
}
export interface TransactionsFilter {
    status?: Variant_disputed_pending_completed;
    fromAmount?: bigint;
    toDate?: bigint;
    toAccountId?: string;
    fromAccountId?: string;
    fromDate?: bigint;
    toAmount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentInput {
    description: string;
    targetAccountId: string;
    amount: bigint;
    sourceAccountId: string;
}
export interface Message {
    messageId: string;
    subject: string;
    createdAt: bigint;
    messageStatus: Variant_read_unread;
    messageText: string;
}
export interface FundTransferInput {
    description: string;
    toAccountId: string;
    fromAccountId: string;
    amount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DashboardSummary {
    recentTransactions: Array<Transaction>;
    unreadMessageCount: bigint;
    totalBalance: bigint;
    accountCount: bigint;
}
export interface UserProfile {
    dateOfBirth: string;
    name: string;
    email: string;
    preferences: string;
    kycStatus: boolean;
    address: string;
    phoneNumber: string;
    idProofBlobId?: string;
}
export interface Transaction {
    status: Variant_disputed_pending_completed;
    transactionType: Variant_transfer_payment;
    date: bigint;
    description: string;
    toAccountId: string;
    fromAccountId: string;
    amount: bigint;
    transactionId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_creditCard_homeLoan_investment_insurance_savings_current {
    creditCard = "creditCard",
    homeLoan = "homeLoan",
    investment = "investment",
    insurance = "insurance",
    savings = "savings",
    current = "current"
}
export enum Variant_disputed_pending_completed {
    disputed = "disputed",
    pending = "pending",
    completed = "completed"
}
export enum Variant_read_unread {
    read = "read",
    unread = "unread"
}
export enum Variant_transfer_payment {
    transfer = "transfer",
    payment = "payment"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAccount(account: Account): Promise<void>;
    addPayee(payee: Payee): Promise<void>;
    addTransaction(transaction: Transaction): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMessage(message: Message): Promise<void>;
    deleteAccount(accountId: string): Promise<void>;
    deleteMessage(messageId: string): Promise<void>;
    deletePayee(payeeId: string): Promise<void>;
    disputeTransaction(transactionId: string): Promise<void>;
    filterTransactions(filter: TransactionsFilter, count: bigint): Promise<Array<Transaction>>;
    fundTransfer(transfer: FundTransferInput): Promise<void>;
    getAccount(accountId: string): Promise<Account>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getMessage(messageId: string): Promise<Message>;
    getProfile(): Promise<UserProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAccounts(): Promise<Array<Account>>;
    listMessages(): Promise<Array<Message>>;
    listPayees(): Promise<Array<Payee>>;
    listTransactions(): Promise<Array<Transaction>>;
    markRead(messageId: string): Promise<void>;
    markUnread(messageId: string): Promise<void>;
    processPayment(payment: PaymentInput): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setKycStatus(status: boolean): Promise<void>;
    updateProfile(profile: UserProfile): Promise<void>;
}
import type { Account as _Account, DashboardSummary as _DashboardSummary, Message as _Message, Transaction as _Transaction, TransactionsFilter as _TransactionsFilter, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAccount(arg0: Account): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccount(to_candid_Account_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccount(to_candid_Account_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPayee(arg0: Payee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayee(arg0);
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_Transaction_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_Transaction_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMessage(arg0: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMessage(to_candid_Message_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMessage(to_candid_Message_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deletePayee(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayee(arg0);
            return result;
        }
    }
    async disputeTransaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disputeTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disputeTransaction(arg0);
            return result;
        }
    }
    async filterTransactions(arg0: TransactionsFilter, arg1: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterTransactions(to_candid_TransactionsFilter_n20(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterTransactions(to_candid_TransactionsFilter_n20(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async fundTransfer(arg0: FundTransferInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fundTransfer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fundTransfer(arg0);
            return result;
        }
    }
    async getAccount(arg0: string): Promise<Account> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccount(arg0);
                return from_candid_Account_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccount(arg0);
            return from_candid_Account_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return from_candid_DashboardSummary_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return from_candid_DashboardSummary_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessage(arg0: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessage(arg0);
                return from_candid_Message_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessage(arg0);
            return from_candid_Message_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_UserProfile_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_UserProfile_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAccounts(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAccounts();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAccounts();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessages();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessages();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPayees(): Promise<Array<Payee>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayees();
            return result;
        }
    }
    async listTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransactions();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransactions();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async markRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRead(arg0);
            return result;
        }
    }
    async markUnread(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markUnread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markUnread(arg0);
            return result;
        }
    }
    async processPayment(arg0: PaymentInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPayment(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setKycStatus(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setKycStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setKycStatus(arg0);
            return result;
        }
    }
    async updateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Account_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardSummary_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardSummary): DashboardSummary {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        disputed: null;
    } | {
        pending: null;
    } | {
        completed: null;
    };
    transactionType: {
        transfer: null;
    } | {
        payment: null;
    };
    date: bigint;
    description: string;
    toAccountId: string;
    fromAccountId: string;
    amount: bigint;
    transactionId: string;
}): {
    status: Variant_disputed_pending_completed;
    transactionType: Variant_transfer_payment;
    date: bigint;
    description: string;
    toAccountId: string;
    fromAccountId: string;
    amount: bigint;
    transactionId: string;
} {
    return {
        status: from_candid_variant_n25(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_variant_n26(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        toAccountId: value.toAccountId,
        fromAccountId: value.fromAccountId,
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    balance: bigint;
    accountId: string;
    createdAt: bigint;
    accountType: {
        creditCard: null;
    } | {
        homeLoan: null;
    } | {
        investment: null;
    } | {
        insurance: null;
    } | {
        savings: null;
    } | {
        current: null;
    };
    accountNumber: string;
}): {
    status: string;
    balance: bigint;
    accountId: string;
    createdAt: bigint;
    accountType: Variant_creditCard_homeLoan_investment_insurance_savings_current;
    accountNumber: string;
} {
    return {
        status: value.status,
        balance: value.balance,
        accountId: value.accountId,
        createdAt: value.createdAt,
        accountType: from_candid_variant_n29(_uploadFile, _downloadFile, value.accountType),
        accountNumber: value.accountNumber
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    name: string;
    email: string;
    preferences: string;
    kycStatus: boolean;
    address: string;
    phoneNumber: string;
    idProofBlobId: [] | [string];
}): {
    dateOfBirth: string;
    name: string;
    email: string;
    preferences: string;
    kycStatus: boolean;
    address: string;
    phoneNumber: string;
    idProofBlobId?: string;
} {
    return {
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        email: value.email,
        preferences: value.preferences,
        kycStatus: value.kycStatus,
        address: value.address,
        phoneNumber: value.phoneNumber,
        idProofBlobId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.idProofBlobId))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recentTransactions: Array<_Transaction>;
    unreadMessageCount: bigint;
    totalBalance: bigint;
    accountCount: bigint;
}): {
    recentTransactions: Array<Transaction>;
    unreadMessageCount: bigint;
    totalBalance: bigint;
    accountCount: bigint;
} {
    return {
        recentTransactions: from_candid_vec_n22(_uploadFile, _downloadFile, value.recentTransactions),
        unreadMessageCount: value.unreadMessageCount,
        totalBalance: value.totalBalance,
        accountCount: value.accountCount
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messageId: string;
    subject: string;
    createdAt: bigint;
    messageStatus: {
        read: null;
    } | {
        unread: null;
    };
    messageText: string;
}): {
    messageId: string;
    subject: string;
    createdAt: bigint;
    messageStatus: Variant_read_unread;
    messageText: string;
} {
    return {
        messageId: value.messageId,
        subject: value.subject,
        createdAt: value.createdAt,
        messageStatus: from_candid_variant_n40(_uploadFile, _downloadFile, value.messageStatus),
        messageText: value.messageText
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    disputed: null;
} | {
    pending: null;
} | {
    completed: null;
}): Variant_disputed_pending_completed {
    return "disputed" in value ? Variant_disputed_pending_completed.disputed : "pending" in value ? Variant_disputed_pending_completed.pending : "completed" in value ? Variant_disputed_pending_completed.completed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transfer: null;
} | {
    payment: null;
}): Variant_transfer_payment {
    return "transfer" in value ? Variant_transfer_payment.transfer : "payment" in value ? Variant_transfer_payment.payment : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditCard: null;
} | {
    homeLoan: null;
} | {
    investment: null;
} | {
    insurance: null;
} | {
    savings: null;
} | {
    current: null;
}): Variant_creditCard_homeLoan_investment_insurance_savings_current {
    return "creditCard" in value ? Variant_creditCard_homeLoan_investment_insurance_savings_current.creditCard : "homeLoan" in value ? Variant_creditCard_homeLoan_investment_insurance_savings_current.homeLoan : "investment" in value ? Variant_creditCard_homeLoan_investment_insurance_savings_current.investment : "insurance" in value ? Variant_creditCard_homeLoan_investment_insurance_savings_current.insurance : "savings" in value ? Variant_creditCard_homeLoan_investment_insurance_savings_current.savings : "current" in value ? Variant_creditCard_homeLoan_investment_insurance_savings_current.current : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    read: null;
} | {
    unread: null;
}): Variant_read_unread {
    return "read" in value ? Variant_read_unread.read : "unread" in value ? Variant_read_unread.unread : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Account>): Array<Account> {
    return value.map((x)=>from_candid_Account_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n38(_uploadFile, _downloadFile, x));
}
function to_candid_Account_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Account): _Account {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Message_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): _Message {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionsFilter_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionsFilter): _TransactionsFilter {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Variant_disputed_pending_completed;
    transactionType: Variant_transfer_payment;
    date: bigint;
    description: string;
    toAccountId: string;
    fromAccountId: string;
    amount: bigint;
    transactionId: string;
}): {
    status: {
        disputed: null;
    } | {
        pending: null;
    } | {
        completed: null;
    };
    transactionType: {
        transfer: null;
    } | {
        payment: null;
    };
    date: bigint;
    description: string;
    toAccountId: string;
    fromAccountId: string;
    amount: bigint;
    transactionId: string;
} {
    return {
        status: to_candid_variant_n13(_uploadFile, _downloadFile, value.status),
        transactionType: to_candid_variant_n14(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        toAccountId: value.toAccountId,
        fromAccountId: value.fromAccountId,
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messageId: string;
    subject: string;
    createdAt: bigint;
    messageStatus: Variant_read_unread;
    messageText: string;
}): {
    messageId: string;
    subject: string;
    createdAt: bigint;
    messageStatus: {
        read: null;
    } | {
        unread: null;
    };
    messageText: string;
} {
    return {
        messageId: value.messageId,
        subject: value.subject,
        createdAt: value.createdAt,
        messageStatus: to_candid_variant_n19(_uploadFile, _downloadFile, value.messageStatus),
        messageText: value.messageText
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: Variant_disputed_pending_completed;
    fromAmount?: bigint;
    toDate?: bigint;
    toAccountId?: string;
    fromAccountId?: string;
    fromDate?: bigint;
    toAmount?: bigint;
}): {
    status: [] | [{
            disputed: null;
        } | {
            pending: null;
        } | {
            completed: null;
        }];
    fromAmount: [] | [bigint];
    toDate: [] | [bigint];
    toAccountId: [] | [string];
    fromAccountId: [] | [string];
    fromDate: [] | [bigint];
    toAmount: [] | [bigint];
} {
    return {
        status: value.status ? candid_some(to_candid_variant_n13(_uploadFile, _downloadFile, value.status)) : candid_none(),
        fromAmount: value.fromAmount ? candid_some(value.fromAmount) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        toAccountId: value.toAccountId ? candid_some(value.toAccountId) : candid_none(),
        fromAccountId: value.fromAccountId ? candid_some(value.fromAccountId) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        toAmount: value.toAmount ? candid_some(value.toAmount) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    name: string;
    email: string;
    preferences: string;
    kycStatus: boolean;
    address: string;
    phoneNumber: string;
    idProofBlobId?: string;
}): {
    dateOfBirth: string;
    name: string;
    email: string;
    preferences: string;
    kycStatus: boolean;
    address: string;
    phoneNumber: string;
    idProofBlobId: [] | [string];
} {
    return {
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        email: value.email,
        preferences: value.preferences,
        kycStatus: value.kycStatus,
        address: value.address,
        phoneNumber: value.phoneNumber,
        idProofBlobId: value.idProofBlobId ? candid_some(value.idProofBlobId) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    balance: bigint;
    accountId: string;
    createdAt: bigint;
    accountType: Variant_creditCard_homeLoan_investment_insurance_savings_current;
    accountNumber: string;
}): {
    status: string;
    balance: bigint;
    accountId: string;
    createdAt: bigint;
    accountType: {
        creditCard: null;
    } | {
        homeLoan: null;
    } | {
        investment: null;
    } | {
        insurance: null;
    } | {
        savings: null;
    } | {
        current: null;
    };
    accountNumber: string;
} {
    return {
        status: value.status,
        balance: value.balance,
        accountId: value.accountId,
        createdAt: value.createdAt,
        accountType: to_candid_variant_n10(_uploadFile, _downloadFile, value.accountType),
        accountNumber: value.accountNumber
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_creditCard_homeLoan_investment_insurance_savings_current): {
    creditCard: null;
} | {
    homeLoan: null;
} | {
    investment: null;
} | {
    insurance: null;
} | {
    savings: null;
} | {
    current: null;
} {
    return value == Variant_creditCard_homeLoan_investment_insurance_savings_current.creditCard ? {
        creditCard: null
    } : value == Variant_creditCard_homeLoan_investment_insurance_savings_current.homeLoan ? {
        homeLoan: null
    } : value == Variant_creditCard_homeLoan_investment_insurance_savings_current.investment ? {
        investment: null
    } : value == Variant_creditCard_homeLoan_investment_insurance_savings_current.insurance ? {
        insurance: null
    } : value == Variant_creditCard_homeLoan_investment_insurance_savings_current.savings ? {
        savings: null
    } : value == Variant_creditCard_homeLoan_investment_insurance_savings_current.current ? {
        current: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_disputed_pending_completed): {
    disputed: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == Variant_disputed_pending_completed.disputed ? {
        disputed: null
    } : value == Variant_disputed_pending_completed.pending ? {
        pending: null
    } : value == Variant_disputed_pending_completed.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_transfer_payment): {
    transfer: null;
} | {
    payment: null;
} {
    return value == Variant_transfer_payment.transfer ? {
        transfer: null
    } : value == Variant_transfer_payment.payment ? {
        payment: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_read_unread): {
    read: null;
} | {
    unread: null;
} {
    return value == Variant_read_unread.read ? {
        read: null
    } : value == Variant_read_unread.unread ? {
        unread: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
